name: medimate
description: "A new Flutter project."

publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  flutter_image_slideshow: ^0.1.6
  syncfusion_flutter_charts: ^29.1.35
  fl_chart: ^0.70.2
  hive_flutter: ^1.1.0
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  tuple: ^2.0.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.2.2
  flutter_slidable: ^3.1.0
  numberpicker: ^2.1.2
  input_quantity: ^2.5.1
  marquee: 2.3.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  markdown_widget: ^2.3.2+8
  flutter_heatmap_calendar: ^1.0.5
  google_fonts: ^6.2.1
  timezone: ^0.10.0
  animated_text_kit: ^4.2.3
  permission_handler: ^12.0.0+1
  firebase_messaging: ^15.2.5
  firebase_database: ^11.3.5
  awesome_notifications: ^0.10.1
  flutter_blue_plus: ^1.35.5
  android_alarm_manager_plus: ^4.0.7
  table_calendar: ^3.2.0
  loading_animation_widget: ^1.3.0
  flutter_local_notifications: ^19.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3



flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/images/google.png
    - assets/light/logo.png
    - assets/dark/logo.png
    - assets/icon.png
    - assets/images/sample_image_1.jpg
    - assets/images/sample_image_2.jpg
    - assets/images/sample_image.png
