// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqPDJlhIic8SoyXfrqdTktYauz0tGJAog',
    appId: '1:35731241256:web:145de56d3410d366be381d',
    messagingSenderId: '35731241256',
    projectId: 'medimate-f69db',
    authDomain: 'medimate-f69db.firebaseapp.com',
    storageBucket: 'medimate-f69db.firebasestorage.app',
    measurementId: 'G-4C5TFX33T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbwXv9CuT8KGzAjvb2m9zBn9Nb7ShWO4c',
    appId: '1:35731241256:android:b53a82970ce082d8be381d',
    messagingSenderId: '35731241256',
    projectId: 'medimate-f69db',
    storageBucket: 'medimate-f69db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPObCn080z4WKU_tV5EU0ZgFPZGxiO1_Q',
    appId: '1:35731241256:ios:d001c738594abd93be381d',
    messagingSenderId: '35731241256',
    projectId: 'medimate-f69db',
    storageBucket: 'medimate-f69db.firebasestorage.app',
    iosClientId: '35731241256-iljvhse9lvsbp4ihg3ga62qsme7a64p3.apps.googleusercontent.com',
    iosBundleId: 'com.example.medimate3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPObCn080z4WKU_tV5EU0ZgFPZGxiO1_Q',
    appId: '1:35731241256:ios:d001c738594abd93be381d',
    messagingSenderId: '35731241256',
    projectId: 'medimate-f69db',
    storageBucket: 'medimate-f69db.firebasestorage.app',
    iosClientId: '35731241256-iljvhse9lvsbp4ihg3ga62qsme7a64p3.apps.googleusercontent.com',
    iosBundleId: 'com.example.medimate3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqPDJlhIic8SoyXfrqdTktYauz0tGJAog',
    appId: '1:35731241256:web:b22860a3571fabe4be381d',
    messagingSenderId: '35731241256',
    projectId: 'medimate-f69db',
    authDomain: 'medimate-f69db.firebaseapp.com',
    storageBucket: 'medimate-f69db.firebasestorage.app',
    measurementId: 'G-ZS06TJR39K',
  );
}
